http://127.0.0.1:5005/

###

http://127.0.0.1:5005/friday

###

POST http://127.0.0.1:5005/friday/score HTTP/1.1
Content-Type: application/json

{
  "score": {
    "fightingCards": 1,
    "defeatedPirates": 1,
    "remainingLifePoints": 1,
    "unbeatenHazards": 1,
    "total": 100
  },
  "isGameWon": true,
  "difficultyLevel": 1
}

###

POST http://127.0.0.1:5005/friday/ping HTTP/1.1


###

http://127.0.0.1:5005/qwertyu

###

